### ISSUE TITLE
Charted songs (in the style of Clone Hero)

### ISSUE THREAD

**Issue by hik4ru** [sightread/sightread#106]
First of all, I know this is quite a hard request being a dev myself (I code on TS too, maybe I could help somehow?) and very out of scope, but also an interesting thought could be made on the long term as there's nothing else like this out there:

As I read you're planning on implementing being able to play local files, what about trying an implementation of MIDI files synced with mp3 files? Kind of what Guitar Hero already before, taking MIDI for the charts and mp3 for the actual music. Keyboard Hero at its fullest.

I get this has some kind of implications that must be studied:
- Moonscraper does that work for Clone/Guitar Hero charts, but it only works for those games format. How could charts be made then? To develop an external editor its an inmense work so it's not viable, but maybe a workaround could be found?
- Performance/syncing issues, I don't know how hard could they hit.
- Not to talk about if the whole project structure already defined can handle something like this.

Sorry for the verbosity, maybe I'm just building castles in the sky but I thought it could be interesting. What's your thought on this?

**Comment by hik4ru** [comment]
(I tried to tag it under 'Enhancement', but wasn't able; sorry about that @samouri)

**Comment by samouri** [comment]
@hik4ru: i've been calling the ability to play a real song in the background a "backing track", and I've already implemented it! I tested it out with Clone Hero charts and it works well, although it is not particularly fun since GH style charts only use 5 notes.

You can check out the unreleased infinite "phrase generator" [here](https://sightread.dev/training/phrases?level=3&clef=treble&generator=eMinor).

The primary challenge to make songs with backing tracks work isn't technical. It's about the content.
1. Using pop music would require licensing, and I have no idea how to do that.
2. We could make our own tracks...but that requires making our own tracks 🙃

**Comment by hik4ru** [comment]
Wow, that's much more than what I expected already!

Of course, to release them would be a no-no because of licensing, unless... There's a public repo where everyone uploads their tracks on their GDrive folders à la Chorus (fightthe pw). 👀

Gotta be honest, I'm extremely grateful to you just for making this kind of Keyboard Hero. I have no issue in working on my own charts (I'm a CH charter already) and I feel like if I find the way to sync MIDIs (or even to make my own ones somehow, I'm a newbie in actual music stuff and never looked into it before) with MP3s, this has a huge chance to be my new hyperfocus for the next weeks. :P

~~Forget about pop tunes tho, classic VGM is what the world really needs~~

**Comment by samouri** [comment]
Let's chat. Ping me on [twitter](https://twitter.com/friednotfrozen) or reddit.

**Comment by hik4ru** [comment]
@samouri Mentioned you on twitter, feel free to DM me!

**Comment by samouri** [comment]
@hik4ru, I don't see anything on twitter. I reached out on IG to the username hik4rens which I'm assuming is you? 😬

**Comment by hik4ru** [comment]
@samouri Oh my god, that's my VERY OLD one (same with this Github account LOL). Search for @kryst4line instead please XD
